### ISSUE TITLE
Add support for Complete cards

### ISSUE THREAD

**Issue by jaron-l** [arakkkkk/kanban.nvim#23]
The Obisidan Kanban plugin has added support for cards to be archived and no longer show in the list. Currently, if a board is using this feature, it will crash kanban.nvim with the following error:
```
Unrecognized line!!
***
```

The unrecognized line is in reference to how Obsidian Kanban keeps track of cards marked as completed. In the list they are currently at, Obsidian Kanban puts all cards marked as completed in subsection of this list as described below:
```
## List Title
- [ ] Example card
**Complete**
- [ x ] Example completed card
***
```
where the line causing the error is the last line.

**Comment by arakkkkk** [comment]
Sorry, I am late replying due to vacation.

Thanks for reporting the Issue.
I was able to confirm the specification that the listing following the following sentence is archived and hidden. We can change kanban.nvim to handle this by tomorrow.
````
***

## Archive
```

I would like to start updating the recognition of completed cards as well.

**Comment by arakkkkk** [comment]
I have modified it so that it can be displayed without error for the tasks that are checked.
However, I have not yet implemented the display and modify the status of the checkboxes from kanban.nvim, nor have I implemented the ability to sort them. 
We will need to consider what kind of specification to make in the future.
