### ISSUE TITLE
Add more information on documentation

### ISSUE THREAD

**Issue by ajsobrino96** [arakkkkk/kanban.nvim#26]
Hi, I installed the plugin because I think that the plugin could improve my productivity, but I cant achieve to work with the plugin.
The documentation is not very good. I dont achieve to write information on the task, remove task,...
who can give me support?

**Comment by arakkkkk** [comment]
Sorry, I do not understand what I am missing in the documentation.
The first step should be to install as a plugin for NeoVim, is this accomplished?

Thank you.

**Comment by arakkkkk** [comment]
@ajsobrino96 Sorry, I may have confused you because the documentation was incorrect. We have corrected the documentation and added the text.

You can create a kanban board with the `KanbanCreate` command. For the content of the task, you only need to enter a string on the card with the neovim operation.

And you can create new task cards with `a`.

Please see https://github.com/arakkkkk/kanban.nvim#usage
