### ISSUE TITLE
Issues when auto commands are set

### ISSUE THREAD

**Issue by sollymay** [arakkkkk/kanban.nvim#27]
Seems like there's an issue with writing into any card/list when Autocommands are set on the open file?

<img width="951" alt="Screenshot 2023-08-01 at 4 00 01 PM" src="https://github.com/arakkkkk/kanban.nvim/assets/6496698/f1fcb238-b779-4eb7-a015-24d3064cbd97">

<img width="951" alt="Screenshot 2023-08-01 at 4 00 09 PM" src="https://github.com/arakkkkk/kanban.nvim/assets/6496698/f9d37501-cf06-48f0-b0b1-2f20078a9333">

**Comment by Pawemix** [comment]
I think this is due to incorrect configuration of `nvim-cmp` that this plugin performs at [kanban.lua, line 56.](https://github.com/arakkkkk/kanban.nvim/blob/28a5b6a8924b6bee9dc8d8fd31a0232267f45e9c/lua/kanban.lua#L56) - it sets `autocomplete` option to `true`, which is an unexpected value according to [nvim-cmp's TriggerEvent type](https://github.com/hrsh7th/nvim-cmp/blob/0b751f6beef40fd47375eaf53d3057e0bfa317e4/lua/cmp/types/cmp.lua#L24). Setting this `true` to `"TextChanged"` resolves the issue.

**Comment by Pawemix** [comment]
<https://github.com/arakkkkk/kanban.nvim/pull/29>
